In [ ]:
# import libraries
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
import pandas as pd
# loading and verifying data
df_gender = pd.read_csv('gender.csv')
df_trend = pd.read_csv('trend.csv')
df_level = pd.read_csv('level.csv')

df_gender.head()
df_trend.head()
df_level.head()

,Sl. No.,State/UT,Primary Drop Out Rate - Boys,Primary Drop Out Rate - Girls,Primary Drop Out Rate - Overall,Upper Primary Drop Out Rate - Boys,Upper Primary Drop Out Rate - Girls,Upper Primary Drop Out Rate - Overall,Secondary Drop Out Rate - Boys,Secondary Drop Out Rate - Girls,Secondary Drop Out Rate - Overall
0,1,Andaman and Nicobar Islands,0.2,0.7,0.4,0.9,1.0,1.0,6.0,3.9,5.0
1,2,Andhra Pradesh,0.0,0.0,0.0,1.7,1.5,1.6,17.5,15.0,16.3
2,3,Arunachal Pradesh,9.3,9.2,9.3,4.8,8.4,6.7,11.2,12.3,11.7
3,4,Assam,6.8,5.2,6.0,10.1,7.6,8.8,19.8,20.7,20.3
4,5,Bihar,0.0,0.0,0.0,4.0,5.2,4.6,19.5,21.4,20.5

In [ ]:
#create copies
df_gender_copy = df_gender.copy()
df_trend_copy = df_trend.copy()
df_level_copy = df_level.copy()

In [ ]:
# inspection of dataset
print("Gender Dataset Shape:" , df_gender_copy.shape)
print("Trend Dataset Shape:" , df_trend_copy.shape)
print("Level Dataset Shape:" , df_level_copy.shape)
print(df_gender_copy.columns)
print(df_trend_copy.columns)
print(df_level_copy.columns)

Gender Dataset Shape: (38, 16)
Trend Dataset Shape: (38, 10)
Level Dataset Shape: (37, 11)
Index(['State/UT', 'Primary level (I - V) - Boys',
       'Primary level (I - V) - Girls', 'Primary level (I - V) - Total',
       'Upper Primary - Boys', 'Upper Primary - Girls',
       'Upper Primary - Total', 'Elementary level (I - VIII) - Boys',
       'Elementary level (I - VIII) - Girls',
       'Elementary level (I - VIII) - Total', 'Secondary (IX-X) - Boys',
       'Secondary (IX-X) - Girls', 'Secondary (IX-X) - Total',
       'Higher Secondary - Boys', 'Higher Secondary - Girls',
       'Higher Secondary - Total'],
      dtype='object')
Index(['State/UT', '2017-18 - Primary', '2017-18 - Upper Primary',
       '2017-18 - Secondary', '2018-19 - Primary', '2018-19 - Upper Primary',
       '2018-19 - Secondary', '2019-20 - Primary', '2019-20 - Upper Primary',
       '2019-20 - Secondary'],
      dtype='object')
Index(['Sl. No.', 'State/UT', 'Primary Drop Out Rate - Boys ',
       'Primary Drop Out Rate - Girls', 'Primary Drop Out Rate - Overall',
       'Upper Primary Drop Out Rate - Boys',
       'Upper Primary Drop Out Rate - Girls',
       'Upper Primary Drop Out Rate - Overall',
       'Secondary Drop Out Rate - Boys ', 'Secondary Drop Out Rate - Girls',
       'Secondary Drop Out Rate - Overall'],
      dtype='object')

In [ ]:
# remove serial number coloumns
df_gender_copy.drop(['Sl. No.'], axis=1, inplace=True, errors='ignore')
df_trend_copy.drop(['Sl. No.'], axis=1, inplace=True, errors='ignore')
df_level_copy.drop(['Sl. No.'], axis=1, inplace=True, errors='ignore')
print(" serial number coloumns removed")
# gender and trend doesn't has sl no

 serial number coloumns removed

In [ ]:
for df in [df_gender_copy, df_trend_copy, df_level_copy]:
  state_col=df.columns[0]
  df.drop(
      df[df[state_col].astype(str)
      .str.strip()
      .str.lower() == 'india']. index, inplace=True)
  print(" India row removed")

 India row removed
 India row removed
 India row removed

In [ ]:
#reset index
df_gender_copy.reset_index(drop=True, inplace=True)
df_trend_copy.reset_index(drop=True, inplace=True)
df_level_copy.reset_index(drop=True, inplace=True)

In [3]:
#standardise state names
df_gender_copy['State/UT'] = df_gender_copy['State/UT'].str.title()
df_trend_copy['State/UT'] = df_trend_copy['State/UT'].str.title()
df_level_copy['State/UT']= df_level_copy['State/UT'].str.title()

NameError: name 'df_gender_copy' is not defined

In [ ]:
# missing values check
print("=======GENDER DATASET=======")
print(df_gender_copy.isnull().sum())
print("=======TREND DATASET=======")
print(df_trend_copy.isnull().sum())
print("=======LEVEL DATASET=======")
print(df_level_copy.isnull().sum())

=======GENDER DATASET=======
State/UT                               0
Primary level (I - V) - Boys           2
Primary level (I - V) - Girls          2
Primary level (I - V) - Total          2
Upper Primary - Boys                   2
Upper Primary - Girls                  2
Upper Primary - Total                  2
Elementary level (I - VIII) - Boys     2
Elementary level (I - VIII) - Girls    2
Elementary level (I - VIII) - Total    2
Secondary (IX-X) - Boys                2
Secondary (IX-X) - Girls               2
Secondary (IX-X) - Total               2
Higher Secondary - Boys                2
Higher Secondary - Girls               2
Higher Secondary - Total               2
dtype: int64
=======TREND DATASET=======
State/UT                   0
2017-18 - Primary          1
2017-18 - Upper Primary    1
2017-18 - Secondary        1
2018-19 - Primary          1
2018-19 - Upper Primary    1
2018-19 - Secondary        1
2019-20 - Primary          0
2019-20 - Upper Primary    0
2019-20 - Secondary        0
dtype: int64
=======LEVEL DATASET=======
State/UT                                 0
Primary Drop Out Rate - Boys             0
Primary Drop Out Rate - Girls            0
Primary Drop Out Rate - Overall          0
Upper Primary Drop Out Rate - Boys       0
Upper Primary Drop Out Rate - Girls      0
Upper Primary Drop Out Rate - Overall    0
Secondary Drop Out Rate - Boys           0
Secondary Drop Out Rate - Girls          0
Secondary Drop Out Rate - Overall        0
dtype: int64

In [ ]:
# converet numeric column
for df in[df_gender_copy, df_trend_copy, df_level_copy]:
  state_col = df.columns[0]
  numeric_cols=[col for col in df.columns if col!=state_col]
  for col in numeric_cols:
    df[col]=pd.to_numeric(df[col], errors='coerce')
    #verify data types
    print(df_gender_copy.info())
    print(df_trend_copy.info())
    print(df_level_copy.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 16 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   State/UT                             38 non-null     object
 1   Primary level (I - V) - Boys         36 non-null     float64
 2   Primary level (I - V) - Girls        36 non-null     float64
 3   Primary level (I - V) - Total        36 non-null     float64
 4   Upper Primary - Boys                 36 non-null     float64
 5   Upper Primary - Girls                36 non-null     float64
 6   Upper Primary - Total                36 non-null     float64
 7   Elementary level (I - VIII) - Boys   36 non-null     float64
 8   Elementary level (I - VIII) - Girls  36 non-null     float64
 9   Elementary level (I - VIII) - Total  36 non-null     float64
 10  Secondary (IX-X) - Boys              36 non-null     float64
 11  Secondary (IX-X) - Girls             36 non-null     float64
 12  Secondary (IX-X) - Total             36 non-null     float64
 13  Higher Secondary - Boys              36 non-null     float64
 14  Higher Secondary - Girls             36 non-null     float64
 15  Higher Secondary - Total             36 non-null     float64
dtypes: float64(15), object(1)
memory usage: 4.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State/UT                 38 non-null     object
 1   2017-18 - Primary        37 non-null     float64
 2   2017-18 - Upper Primary  37 non-null     float64
 3   2017-18 - Secondary      37 non-null     float64
 4   2018-19 - Primary        37 non-null     float64
 5   2018-19 - Upper Primary  37 non-null     float64
 6   2018-19 - Secondary      37 non-null     float64
 7   2019-20 - Primary        38 non-null     float64
 8   2019-20 - Upper Primary  38 non-null     float64
 9   2019-20 - Secondary      38 non-null     float64
dtypes: float64(9), object(1)
memory usage: 3.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 10 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   State/UT                               36 non-null     object
 1   Primary Drop Out Rate - Boys           36 non-null     float64
 2   Primary Drop Out Rate - Girls          36 non-null     float64
 3   Primary Drop Out Rate - Overall        36 non-null     float64
 4   Upper Primary Drop Out Rate - Boys     36 non-null     float64
 5   Upper Primary Drop Out Rate - Girls    36 non-null     float64
 6   Upper Primary Drop Out Rate - Overall  36 non-null     float64
 7   Secondary Drop Out Rate - Boys         36 non-null     float64
 8   Secondary Drop Out Rate - Girls        36 non-null     float64
 9   Secondary Drop Out Rate - Overall      36 non-null     float64
dtypes: float64(9), object(1)
memory usage: 2.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 16 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   State/UT                             38 non-null     object
 1   Primary level (I - V) - Boys         36 non-null     float64
 2   Primary level (I - V) - Girls        36 non-null     float64
 3   Primary level (I - V) - Total        36 non-null     float64
 4   Upper Primary - Boys                 36 non-null     float64
 5   Upper Primary - Girls                36 non-null     float64
 6   Upper Primary - Total                36 non-null     float64
 7   Elementary level (I - VIII) - Boys   36 non-null     float64
 8   Elementary level (I - VIII) - Girls  36 non-null     float64
 9   Elementary level (I - VIII) - Total  36 non-null     float64
 10  Secondary (IX-X) - Boys              36 non-null     float64
 11  Secondary (IX-X) - Girls             36 non-null     float64
 12  Secondary (IX-X) - Total             36 non-null     float64
 13  Higher Secondary - Boys              36 non-null     float64
 14  Higher Secondary - Girls             36 non-null     float64
 15  Higher Secondary - Total             36 non-null     float64
dtypes: float64(15), object(1)
memory usage: 4.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State/UT                 38 non-null     object
 1   2017-18 - Primary        37 non-null     float64
 2   2017-18 - Upper Primary  37 non-null     float64
 3   2017-18 - Secondary      37 non-null     float64
 4   2018-19 - Primary        37 non-null     float64
 5   2018-19 - Upper Primary  37 non-null     float64
 6   2018-19 - Secondary      37 non-null     float64
 7   2019-20 - Primary        38 non-null     float64
 8   2019-20 - Upper Primary  38 non-null     float64
 9   2019-20 - Secondary      38 non-null     float64
dtypes: float64(9), object(1)
memory usage: 3.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 10 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   State/UT                               36 non-null     object
 1   Primary Drop Out Rate - Boys           36 non-null     float64
 2   Primary Drop Out Rate - Girls          36 non-null     float64
 3   Primary Drop Out Rate - Overall        36 non-null     float64
 4   Upper Primary Drop Out Rate - Boys     36 non-null     float64
 5   Upper Primary Drop Out Rate - Girls    36 non-null     float64
 6   Upper Primary Drop Out Rate - Overall  36 non-null     float64
 7   Secondary Drop Out Rate - Boys         36 non-null     float64
 8   Secondary Drop Out Rate - Girls        36 non-null     float64
 9   Secondary Drop Out Rate - Overall      36 non-null     float64
dtypes: float64(9), object(1)
memory usage: 2.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 16 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   State/UT                             38 non-null     object
 1   Primary level (I - V) - Boys         36 non-null     float64
 2   Primary level (I - V) - Girls        36 non-null     float64
 3   Primary level (I - V) - Total        36 non-null     float64
 4   Upper Primary - Boys                 36 non-null     float64
 5   Upper Primary - Girls                36 non-null     float64
 6   Upper Primary - Total                36 non-null     float64
 7   Elementary level (I - VIII) - Boys   36 non-null     float64
 8   Elementary level (I - VIII) - Girls  36 non-null     float64
 9   Elementary level (I - VIII) - Total  36 non-null     float64
 10  Secondary (IX-X) - Boys              36 non-null     float64
 11  Secondary (IX-X) - Girls             36 non-null     float64
 12  Secondary (IX-X) - Total             36 non-null     float64
 13  Higher Secondary - Boys              36 non-null     float64
 14  Higher Secondary - Girls             36 non-null     float64
 15  Higher Secondary - Total             36 non-null     float64
dtypes: float64(15), object(1)
memory usage: 4.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State/UT                 38 non-null     object
 1   2017-18 - Primary        37 non-null     float64
 2   2017-18 - Upper Primary  37 non-null     float64
 3   2017-18 - Secondary      37 non-null     float64
 4   2018-19 - Primary        37 non-null     float64
 5   2018-19 - Upper Primary  37 non-null     float64
 6   2018-19 - Secondary      37 non-null     float64
 7   2019-20 - Primary        38 non-null     float64
 8   2019-20 - Upper Primary  38 non-null     float64
 9   2019-20 - Secondary      38 non-null     float64
dtypes: float64(9), object(1)
memory usage: 3.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 10 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   State/UT                               36 non-null     object
 1   Primary Drop Out Rate - Boys           36 non-null     float64
 2   Primary Drop Out Rate - Girls          36 non-null     float64
 3   Primary Drop Out Rate - Overall        36 non-null     float64
 4   Upper Primary Drop Out Rate - Boys     36 non-null     float64
 5   Upper Primary Drop Out Rate - Girls    36 non-null     float64
 6   Upper Primary Drop Out Rate - Overall  36 non-null     float64
 7   Secondary Drop Out Rate - Boys         36 non-null     float64
 8   Secondary Drop Out Rate - Girls        36 non-null     float64
 9   Secondary Drop Out Rate - Overall      36 non-null     float64
dtypes: float64(9), object(1)
memory usage: 2.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 16 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   State/UT                             38 non-null     object
 1   Primary level (I - V) - Boys         36 non-null     float64
 2   Primary level (I - V) - Girls        36 non-null     float64
 3   Primary level (I - V) - Total        36 non-null     float64
 4   Upper Primary - Boys                 36 non-null     float64
 5   Upper Primary - Girls                36 non-null     float64
 6   Upper Primary - Total                36 non-null     float64
 7   Elementary level (I - VIII) - Boys   36 non-null     float64
 8   Elementary level (I - VIII) - Girls  36 non-null     float64
 9   Elementary level (I - VIII) - Total  36 non-null     float64
 10  Secondary (IX-X) - Boys              36 non-null     float64
 11  Secondary (IX-X) - Girls             36 non-null     float64
 12  Secondary (IX-X) - Total             36 non-null     float64
 13  Higher Secondary - Boys              36 non-null     float64
 14  Higher Secondary - Girls             36 non-null     float64
 15  Higher Secondary - Total             36 non-null     float64
dtypes: float64(15), object(1)
memory usage: 4.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State/UT                 38 non-null     object
 1   2017-18 - Primary        37 non-null     float64
 2   2017-18 - Upper Primary  37 non-null     float64
 3   2017-18 - Secondary      37 non-null     float64
 4   2018-19 - Primary        37 non-null     float64
 5   2018-19 - Upper Primary  37 non-null     float64
 6   2018-19 - Secondary      37 non-null     float64
 7   2019-20 - Primary        38 non-null     float64
 8   2019-20 - Upper Primary  38 non-null     float64
 9   2019-20 - Secondary      38 non-null     float64
dtypes: float64(9), object(1)
memory usage: 3.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 10 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   State/UT                               36 non-null     object
 1   Primary Drop Out Rate - Boys           36 non-null     float64
 2   Primary Drop Out Rate - Girls          36 non-null     float64
 3   Primary Drop Out Rate - Overall        36 non-null     float64
 4   Upper Primary Drop Out Rate - Boys     36 non-null     float64
 5   Upper Primary Drop Out Rate - Girls    36 non-null     float64
 6   Upper Primary Drop Out Rate - Overall  36 non-null     float64
 7   Secondary Drop Out Rate - Boys         36 non-null     float64
 8   Secondary Drop Out Rate - Girls        36 non-null     float64
 9   Secondary Drop Out Rate - Overall      36 non-null     float64
dtypes: float64(9), object(1)
memory usage: 2.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 16 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   State/UT                             38 non-null     object
 1   Primary level (I - V) - Boys         36 non-null     float64
 2   Primary level (I - V) - Girls        36 non-null     float64
 3   Primary level (I - V) - Total        36 non-null     float64
 4   Upper Primary - Boys                 36 non-null     float64
 5   Upper Primary - Girls                36 non-null     float64
 6   Upper Primary - Total                36 non-null     float64
 7   Elementary level (I - VIII) - Boys   36 non-null     float64
 8   Elementary level (I - VIII) - Girls  36 non-null     float64
 9   Elementary level (I - VIII) - Total  36 non-null     float64
 10  Secondary (IX-X) - Boys              36 non-null     float64
 11  Secondary (IX-X) - Girls             36 non-null     float64
 12  Secondary (IX-X) - Total             36 non-null     float64
 13  Higher Secondary - Boys              36 non-null     float64
 14  Higher Secondary - Girls             36 non-null     float64
 15  Higher Secondary - Total             36 non-null     float64
dtypes: float64(15), object(1)
memory usage: 4.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State/UT                 38 non-null     object
 1   2017-18 - Primary        37 non-null     float64
 2   2017-18 - Upper Primary  37 non-null     float64
 3   2017-18 - Secondary      37 non-null     float64
 4   2018-19 - Primary        37 non-null     float64
 5   2018-19 - Upper Primary  37 non-null     float64
 6   2018-19 - Secondary      37 non-null     float64
 7   2019-20 - Primary        38 non-null     float64
 8   2019-20 - Upper Primary  38 non-null     float64
 9   2019-20 - Secondary      38 non-null     float64
dtypes: float64(9), object(1)
memory usage: 3.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 10 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   State/UT                               36 non-null     object
 1   Primary Drop Out Rate - Boys           36 non-null     float64
 2   Primary Drop Out Rate - Girls          36 non-null     float64
 3   Primary Drop Out Rate - Overall        36 non-null     float64
 4   Upper Primary Drop Out Rate - Boys     36 non-null     float64
 5   Upper Primary Drop Out Rate - Girls    36 non-null     float64
 6   Upper Primary Drop Out Rate - Overall  36 non-null     float64
 7   Secondary Drop Out Rate - Boys         36 non-null     float64
 8   Secondary Drop Out Rate - Girls        36 non-null     float64
 9   Secondary Drop Out Rate - Overall      36 non-null     float64
dtypes: float64(9), object(1)
memory usage: 2.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 16 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   State/UT                             38 non-null     object
 1   Primary level (I - V) - Boys         36 non-null     float64
 2   Primary level (I - V) - Girls        36 non-null     float64
 3   Primary level (I - V) - Total        36 non-null     float64
 4   Upper Primary - Boys                 36 non-null     float64
 5   Upper Primary - Girls                36 non-null     float64
 6   Upper Primary - Total                36 non-null     float64
 7   Elementary level (I - VIII) - Boys   36 non-null     float64
 8   Elementary level (I - VIII) - Girls  36 non-null     float64
 9   Elementary level (I - VIII) - Total  36 non-null     float64
 10  Secondary (IX-X) - Boys              36 non-null     float64
 11  Secondary (IX-X) - Girls             36 non-null     float64
 12  Secondary (IX-X) - Total             36 non-null     float64
 13  Higher Secondary - Boys              36 non-null     float64
 14  Higher Secondary - Girls             36 non-null     float64
 15  Higher Secondary - Total             36 non-null     float64
dtypes: float64(15), object(1)
memory usage: 4.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State/UT                 38 non-null     object
 1   2017-18 - Primary        37 non-null     float64
 2   2017-18 - Upper Primary  37 non-null     float64
 3   2017-18 - Secondary      37 non-null     float64
 4   2018-19 - Primary        37 non-null     float64
 5   2018-19 - Upper Primary  37 non-null     float64
 6   2018-19 - Secondary      37 non-null     float64
 7   2019-20 - Primary        38 non-null     float64
 8   2019-20 - Upper Primary  38 non-null     float64
 9   2019-20 - Secondary      38 non-null     float64
dtypes: float64(9), object(1)
memory usage: 3.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 10 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   State/UT                               36 non-null     object
 1   Primary Drop Out Rate - Boys           36 non-null     float64
 2   Primary Drop Out Rate - Girls          36 non-null     float64
 3   Primary Drop Out Rate - Overall        36 non-null     float64
 4   Upper Primary Drop Out Rate - Boys     36 non-null     float64
 5   Upper Primary Drop Out Rate - Girls    36 non-null     float64
 6   Upper Primary Drop Out Rate - Overall  36 non-null     float64
 7   Secondary Drop Out Rate - Boys         36 non-null     float64
 8   Secondary Drop Out Rate - Girls        36 non-null     float64
 9   Secondary Drop Out Rate - Overall      36 non-null     float64
dtypes: float64(9), object(1)
memory usage: 2.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 16 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   State/UT                             38 non-null     object
 1   Primary level (I - V) - Boys         36 non-null     float64
 2   Primary level (I - V) - Girls        36 non-null     float64
 3   Primary level (I - V) - Total        36 non-null     float64
 4   Upper Primary - Boys                 36 non-null     float64
 5   Upper Primary - Girls                36 non-null     float64
 6   Upper Primary - Total                36 non-null     float64
 7   Elementary level (I - VIII) - Boys   36 non-null     float64
 8   Elementary level (I - VIII) - Girls  36 non-null     float64
 9   Elementary level (I - VIII) - Total  36 non-null     float64
 10  Secondary (IX-X) - Boys              36 non-null     float64
 11  Secondary (IX-X) - Girls             36 non-null     float64
 12  Secondary (IX-X) - Total             36 non-null     float64
 13  Higher Secondary - Boys              36 non-null     float64
 14  Higher Secondary - Girls             36 non-null     float64
 15  Higher Secondary - Total             36 non-null     float64

In [ ]:
# descriptive stats
print("=======GENDER DATASET=======")
print(df_gender_copy.describe())
print("=======TREND DATASET=======")
print(df_trend_copy.describe())
print("=======LEVEL DATASET=======")
print(df_level_copy.describe())

=======GENDER DATASET=======
       Primary level (I - V) - Boys  Primary level (I - V) - Girls  \
count                     36.000000                      36.000000
mean                       3.783333                       3.405556
std                        4.201530                       4.126981
min                        0.000000                       0.000000
25%                        0.375000                       0.375000
50%                        2.900000                       2.550000
75%                        4.975000                       4.925000
max                       18.900000                      19.200000

       Primary level (I - V) - Total  Upper Primary - Boys  \
count                      36.000000             36.000000
mean                        3.569444              4.783333
std                         4.141347              5.135674
min                         0.000000              0.000000
25%                         0.250000              0.475000
50%                         2.500000              3.300000
75%                         4.925000              7.050000
max                        19.000000             22.400000

       Upper Primary - Girls  Upper Primary - Total  \
count              36.000000              36.000000
mean                4.719444               4.586111
std                 5.198287               5.190054
min                 0.000000               0.000000
25%                 0.875000               0.575000
50%                 3.750000               3.350000
75%                 6.300000               6.725000
max                25.900000              24.100000

       Elementary level (I - VIII) - Boys  \
count                           36.000000
mean                             4.069444
std                              4.312826
min                              0.000000
25%                              0.375000
50%                              3.250000
75%                              6.500000
max                             20.000000

       Elementary level (I - VIII) - Girls  \
count                            36.000000
mean                              3.783333
std                               4.233101
min                               0.000000
25%                               0.550000
50%                               3.200000
75%                               5.400000
max                              21.200000

       Elementary level (I - VIII) - Total  Secondary (IX-X) - Boys  \
count                            36.000000                36.000000
mean                              3.883333                21.394444
std                               4.257732                10.261939
min                               0.000000                 0.000000
25%                               0.675000                13.675000
50%                               3.150000                21.950000
75%                               5.925000                27.950000
max                              20.600000                41.000000

       Secondary (IX-X) - Girls  Secondary (IX-X) - Total  \
count                 36.000000                 36.000000
mean                  19.494444                 20.600000
std                   10.243910                  9.634907
min                    0.000000                  0.000000
25%                   13.975000                 15.600000
50%                   20.800000                 20.850000
75%                   24.000000                 26.825000
max                   46.000000                 43.300000

       Higher Secondary - Boys  Higher Secondary - Girls  \
count                36.000000                  36.00000
mean                  7.958333                   5.42500
std                   9.507392                   9.05811
min                   0.000000                   0.00000
25%                   0.000000                   0.00000
50%                   4.600000                   3.15000
75%                  12.000000                   6.37500
max                  43.200000                  50.60000

       Higher Secondary - Total
count                 36.000000
mean                   6.611111
std                    9.000279
min                    0.000000
25%                    0.225000
50%                    3.800000
75%                    9.375000
max                   46.500000
=======TREND DATASET=======
       2017-18 - Primary  2017-18 - Upper Primary  2017-18 - Secondary  \
count          37.000000                37.000000            37.000000
mean            2.543243                 3.227027            16.335135
std             2.765817                 3.154155             7.878495
min             0.000000                 0.000000             0.000000
25%             0.100000                 0.500000            11.400000
50%             1.700000                 2.400000            17.100000
75%             3.500000                 5.400000            20.600000
max            10.100000                13.300000            33.700000

       2018-19 - Primary  2018-19 - Upper Primary  2018-19 - Secondary  \
count          37.000000                37.000000            37.000000
mean            3.659459                 3.383784            17.418919
std             4.102266                 3.151764             7.447962
min             0.000000                 0.000000             4.500000
25%             0.300000                 0.900000            12.700000
50%             3.100000                 2.900000            16.400000
75%             5.400000                 5.000000            22.300000
max            16.900000                12.400000            36.000000

       2019-20 - Primary  2019-20 - Upper Primary  2019-20 - Secondary
count          38.000000                38.000000            38.000000
mean            1.857895                 2.350000            15.684211
std             2.474260                 2.636516             7.713047
min             0.000000                 0.000000             0.000000
25%             0.000000                 0.025000             9.750000
50%             0.850000                 1.650000            15.450000
75%             2.650000                 3.725000            21.000000
max             8.800000                 8.900000            34.300000
=======LEVEL DATASET=======
       Primary Drop Out Rate - Boys   Primary Drop Out Rate - Girls  \
count                      36.000000                      36.000000
mean                        2.716667                       2.291667
std                         3.676683                       3.284020
min                         0.000000                       0.000000
25%                         0.000000                       0.000000
50%                         1.000000                       0.550000
75%                         3.825000                       3.725000
max                        13.500000                      13.000000

       Primary Drop Out Rate - Overall  Upper Primary Drop Out Rate - Boys  \
count                        36.000000                           36.000000
mean                          2.513889                            3.258333
std                           3.467000                            3.141826
min                           0.000000                            0.000000
25%                           0.000000                            0.525000
50%                           0.800000                            2.900000
75%                           3.775000                            4.650000
max                          13.300000                           12.000000

       Upper Primary Drop Out Rate - Girls  \
count                            36.000000
mean                              3.002778
std                               2.890525
min                               0.000000
25%                               0.150000
50%                               2.250000
75%                               4.825000
max                               9.400000

       Upper Primary Drop Out Rate - Overall  Secondary Drop Out Rate - Boys   \
count                              36.000000                        36.000000
mean                                3.130556                        11.219444
std                                 2.945391                         6.811747
min                                 0.000000                         0.000000
25%                                 0.500000                         6.225000
50%                                 2.700000                        10.550000
75%                                 4.525000                        16.525000
max                                10.600000                        29.200000

       Secondary Drop Out Rate - Girls  Secondary Drop Out Rate - Overall
count                        36.000000                          36.000000
mean                          9.605556                          10.425000
std                           6.509595                           6.600189
min                           0.000000                           0.000000
25%                           4.475000                           5.375000
50%                           8.650000                           9.600000
75%                          13.500000                          15.100000
max                          25.200000                          27.300000

In [ ]:
#duplicate check
print(" gender duplicates:",df_gender_copy.duplicated().sum())
print(" trend duplicates:",df_trend_copy.duplicated().sum())
print(" level duplicates:",df_level_copy.duplicated().sum())

 gender duplicates: 0
 trend duplicates: 0
 level duplicates: 0

In [ ]:
# state coverage comparision
states_gender= set(df_gender_copy.iloc[:,0])
states_trend= set(df_trend_copy.iloc[:,0])
states_level= set(df_level_copy.iloc[:,0])
print( "States in Gender:",len(states_gender))
print( "States in Trend:",len(states_trend))
print( "States in Level:",len(states_level))

States in Gender: 38
States in Trend: 38
States in Level: 36

In [ ]:
#states missing across datasets
print (" Present in gender but not in trend ")
print(states_gender-states_trend)
print (" Present in trend but not in level ")
print(states_trend-states_level)
print (" Present in level but not in gender ")
print(states_level-states_gender)

 Present in gender but not in trend
{'Uttaranchal', 'Pondicherry', 'Orissa'}
 Present in trend but not in level
{'Daman & Diu', 'Jammu & Kashmir', 'Total', 'Andaman & Nicobar Islands', 'Dadra & Nagar Haveli'}
 Present in level but not in gender
{'Dadra And Nagar Haveli And Daman And Diu', 'Odisha', 'Jammu And Kashmir', 'Andaman And Nicobar Islands', 'Uttarakhand', 'Puducherry'}

In [ ]:
# check suspicious zero value
for col in df_gender_copy.columns[1:]:
  zeros = (df_gender_copy[col]==0).sum()
  print(f"{col}: {zeros}")

Primary level (I - V) - Boys: 8
Primary level (I - V) - Girls: 9
Primary level (I - V) - Total: 7
Upper Primary - Boys: 8
Upper Primary - Girls: 7
Upper Primary - Total: 8
Elementary level (I - VIII) - Boys: 9
Elementary level (I - VIII) - Girls: 7
Elementary level (I - VIII) - Total: 7
Secondary (IX-X) - Boys: 1
Secondary (IX-X) - Girls: 1
Secondary (IX-X) - Total: 1
Higher Secondary - Boys: 10
Higher Secondary - Girls: 13
Higher Secondary - Total: 9

In [ ]:
# secondary education data set
secondary_level = df_level_copy[
   [ df_level_copy.columns[0],
    'Secondary Drop Out Rate - Boys ',
    'Secondary Drop Out Rate - Girls',
    'Secondary Drop Out Rate - Overall'
   ]
]
secondary_level.head()

,State/UT,Secondary Drop Out Rate - Boys,Secondary Drop Out Rate - Girls,Secondary Drop Out Rate - Overall
0,Andaman And Nicobar Islands,6.0,3.9,5.0
1,Andhra Pradesh,17.5,15.0,16.3
2,Arunachal Pradesh,11.2,12.3,11.7
3,Assam,19.8,20.7,20.3
4,Bihar,19.5,21.4,20.5

In [ ]:
# save cleaned files
df_gender_copy.to_csv('gender_cleaned.csv', index=False)
df_trend_copy.to_csv('trend_cleaned.csv', index=False)
df_level_copy.to_csv('level_cleaned.csv', index=False)
print(" All cleaned files saved successfully")

 All cleaned files saved successfully

In [ ]:
# download cleaned files
from google.colab import files
files.download('gender_cleaned.csv')
files.download('trend_cleaned.csv')
files.download('level_cleaned.csv')